name: Build and publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: yarn
        - name: Build packages
          run: yarn build

    
